### ISSUE TITLE
rpm changes ownership to root

### ISSUE THREAD

**Issue by tsmeele** [UtrechtUniversity/irods-sudo-microservices#2]
As a side effect of the installation of the rpm, ownership of the directories /var/lib/irods and the directory /var/lib/irods/plugins and its content is changed to user root while these dirs should remain owned by the irods service account.

**Comment by cjsmeele** [comment]
For `/etc/irods`, this is solved / worked around in [4.2.1_1.0.0](https://github.com/UtrechtUniversity/irods-sudo-microservices/releases/tag/4.2.1_1.0.0).
With CPack, we can neither leave the permissions alone nor specify `irods:irods` as the owner (as that conflicts with the `root:root` ownership set in the iRODS package (which is later overridden by the setup script)).
Instead we use a post-install script to change the owner back to irods (this assumes `irods` is the name of the service account).

`/var/lib/irods` is no longer an issue as the msi plugin directory now resides under `/usr/lib/irods` which has `root` ownership by default.
