### ISSUE TITLE
please add support for iRODS 4.2.x

### ISSUE THREAD

**Issue by hurngchunlee** [UtrechtUniversity/irods-sudo-microservices#3]

**Comment by cjsmeele** [comment]
We have just released [4.2.1_1.0.0](https://github.com/UtrechtUniversity/irods-sudo-microservices/releases/tag/4.2.1_1.0.0) which is compatible with iRODS version 4.2.1.

Note that in this release the parameters for `msiSudoObjAclSet` and `msiSudoObjMetaRemove` have changed slightly: `*recursive` and `*wildcards` used to allow integer `0`/`1` values, now they only accept `"recursive"` / `"wildcards"` strings to enable them and empty strings `""` to disable them.

Please let us know if you have any issues with the new version.

**Comment by hurngchunlee** [comment]
Hi Chris, thank you for the release.  I have been using it for few days, and the microservices we have been using seem to work with iRODS 4.2.1.
