### ISSUE TITLE
release for iRODS 4.2.2?

### ISSUE THREAD

**Issue by hurngchunlee** [UtrechtUniversity/irods-sudo-microservices#4]
Hi,

I wonder if there is a plan of a new release for iRODS 4.2.2? or we should build it ourselves? Thanks!

Hong

**Comment by cjsmeele** [comment]
Hi Hong, sorry for the late response. 
We've now officially released a [4.2.2 sudo package](https://github.com/UtrechtUniversity/irods-sudo-microservices/releases/tag/4.2.2_1.0.0). It is identical in interface and features to 4.2.1_1.0.0.
Cheers, Chris
